### ISSUE TITLE
Text Editor

### ISSUE THREAD

**Issue by C4Wiz** [jlesage/docker-filezilla#1]
please add a text viewer/editor IE: nano

**Comment by jlesage** [comment]
You mean a test editor that can be launched via the FileZilla interface?

**Comment by C4Wiz** [comment]
Exactly

David Smythe
Sent from my  iPhone 7 Plus on iOS 10

On Jul 30, 2017, at 6:37 PM, Jocelyn Le Sage <notifications@github.com<mailto:notifications@github.com>> wrote:


You mean a test editor that can be launched via the FileZilla interface?

**Comment by jlesage** [comment]
Text editor added with the latest version!

**Comment by C4Wiz** [comment]
editor does not work with mpls files

in Filezilla container:
![screen shot 2017-07-31 at 15 42 44](https://user-images.githubusercontent.com/3883521/28799707-eff953bc-7606-11e7-84a5-8b52e41162a3.png)


in osx:
![screen shot 2017-07-31 at 15 41 10](https://user-images.githubusercontent.com/3883521/28799675-c88295c8-7606-11e7-9d61-3cc0a022c3b6.png)

**Comment by jlesage** [comment]
I think it's because mpls are binary files...  Do you need to edit them?

**Comment by C4Wiz** [comment]
it is a text based file, i need to view them at least

**Comment by jlesage** [comment]
If we talk about the playlists from blu-ray discs, they are not text-based files.  That seems to be the case with the screenshot you provided, where there are a lot of weird characters.
If you run `cat 00800.mpls`, does it give you a nice output?

**Comment by jlesage** [comment]
We would need a text editor that also supports binary files.  With the exception of `nano` an `vi` (which are more difficult to use for average users), I don't know if there are other ones.

**Comment by C4Wiz** [comment]
here is the mpls file, i had to add .txt so it would upload

[00800.mpls.txt](https://github.com/jlesage/docker-filezilla/files/1189071/00800.mpls.txt)

**Comment by C4Wiz** [comment]
they open in textedit on mac and notepad on windows

**Comment by jlesage** [comment]
Text editors behave differently.  Some display garbage when trying to display unprintable characters, while other seems to just hide them.

May I know what is your use case?  Why you need to view these files?

**Comment by C4Wiz** [comment]
So i can see the correct m2ts file

David Smythe
Sent from my  iPhone 7 Plus on iOS 10

On Jul 31, 2017, at 6:17 PM, Jocelyn Le Sage <notifications@github.com<mailto:notifications@github.com>> wrote:


Text editors behave differently. Some display garbage when trying to display unprintable characters, while other seems to just hide them.

May I know what is your use case? Why you need to view these files?

**Comment by jlesage** [comment]
Sorry not sure to understand... how the content of a mpls can help you with m2ts files?

**Comment by C4Wiz** [comment]
The mpls lists all the mt2s files for the movie

**Comment by jlesage** [comment]
Yes, but when opened with a text editor, we get nothing useful (as shown on your mac screenshot)...?

**Comment by C4Wiz** [comment]
sure it is, listed plain as can be, see the hilighted text:

<img width="639" alt="screen shot 2017-07-31 at 6 56 16 pm" src="https://user-images.githubusercontent.com/3883521/28804684-0c47083c-7622-11e7-9304-c768403d7714.png">

**Comment by jlesage** [comment]
Ok I see.

So I will try to see if there is any other text editor replacement that could do the job...  Are you familiar with `vi`?  There is a graphical version of it, `gvim`.  If I find nothing else, I could add this one as a second text editor that "advanced" users could use.

**Comment by C4Wiz** [comment]
i prefer nano, but gvim will work, also gedit works

**Comment by jlesage** [comment]
I think nano must be run in a terminal (no graphical version).  gedit is not available on Alpine Linux, but I could check if compiling from source is possible, without pulling too much dependencies.
