### ISSUE TITLE
UI Cant Be Reached

### ISSUE THREAD

**Issue by wesmannmsu** [jlesage/docker-filezilla#11]
I have Filezilla installed and its says its running, but when I try to access the UI, the page that opens says "This site can’t be reached"

Trying to stop the containing results in the green play button changing to a spinning thing, forever, it never stops until it crashes

This is everything in the log

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[services.d] stopping services
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.

**Comment by jlesage** [comment]
What are the container settings?

**Comment by wesmannmsu** [comment]
The Container settings are the defaults except I added these three

Container Path: /UNRAID   =  /mnt/
Container Path: /UNASSIGNED   =  /mnt/disks
Container Path: /FLASH   =  /boot/


--

**Comment by wesmannmsu** [comment]
Any Ideas?

**Comment by jlesage** [comment]
Which version of unRAID are you running?  It should work for sure.  I would try to re-create the container using default settings.  Make sure to start with a clean appdata folder.

**Comment by wesmannmsu** [comment]
I am running Unraid 6.7.2

I complete uninstalled the Docker, then reinstalled the docker with the default template. 

<img width="1531" alt="Screen Shot 2019-10-08 at 8 04 34 AM" src="https://user-images.githubusercontent.com/55263090/66398059-b3addb00-e9a2-11e9-8fb0-2934ebe2766b.png">

it shows its running

<img width="1547" alt="Screen Shot 2019-10-08 at 8 05 33 AM" src="https://user-images.githubusercontent.com/55263090/66398221-038ca200-e9a3-11e9-8db3-340511116493.png">

but then I click on Web UI, i get "This site can’t be reached192.168.29.29 refused to connect. Search Google for 192 168 7809 ERR_CONNECTION_REFUSED"

**Comment by wesmannmsu** [comment]
again, trying to stop it, it just spins and spins, then crashes

**Comment by jlesage** [comment]
Could you provide the output of:

- `docker insect FileZilla`
- `docker logs FileZilla`

Also, what do you mean exactly by "it crashes"?

**Comment by wesmannmsu** [comment]
Yes, of course, my crash I mean, it sometimes disappears from the docker tab until I reboot. otherwise, it just shows back up as running and doesn't stop, or reboots. 

root@HardHome:~# docker inspect FileZilla
[
    {
        "Id": "1d986da4ddeee5334d99d0d118f65c16c891f8586e835fbccad30b6960fce735",
        "Created": "2019-10-08T13:04:45.461070843Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 13065,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-10-09T01:47:19.624022407Z",
            "FinishedAt": "2019-10-08T13:26:02.21468084Z"
        },
        "Image": "sha256:771eb406a83368fd9f6c79f2caaf3aec8811ccc74cf77cc309c1541c85089bb2",
        "ResolvConfPath": "/var/lib/docker/containers/1d986da4ddeee5334d99d0d118f65c16c891f8586e835fbccad30b6960fce735/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/1d986da4ddeee5334d99d0d118f65c16c891f8586e835fbccad30b6960fce735/hostname",
        "HostsPath": "/var/lib/docker/containers/1d986da4ddeee5334d99d0d118f65c16c891f8586e835fbccad30b6960fce735/hosts",
        "LogPath": "/var/lib/docker/containers/1d986da4ddeee5334d99d0d118f65c16c891f8586e835fbccad30b6960fce735/1d986da4ddeee5334d99d0d118f65c16c891f8586e835fbccad30b6960fce735-json.log",
        "Name": "/FileZilla",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/mnt/user:/storage:rw",
                "/mnt/user/appdata/FileZilla:/config:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7809"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7909"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/user/appdata/FileZilla",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/user",
                "Destination": "/storage",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "1d986da4ddee",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "HOST_OS=Unraid",
                "USER_ID=99",
                "UMASK=000",
                "DISPLAY_HEIGHT=768",
                "SECURE_CONNECTION=0",
                "X11VNC_EXTRA_OPTS=",
                "TZ=America/Chicago",
                "GROUP_ID=100",
                "APP_NICENESS=",
                "DISPLAY_WIDTH=1280",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "APP_NAME=FileZilla",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0"
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "jlesage/filezilla",
            "Volumes": {
                "/config": {},
                "/storage": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2019-09-25T15:39:19Z",
                "org.label-schema.description": "Docker container for FileZilla",
                "org.label-schema.name": "filezilla",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "de8dc7ee25c85988c9b9fe49909b92b1b5781804",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-filezilla.git",
                "org.label-schema.version": "1.21.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "e1af8f893da4ccad026368845dc37e9e452a7e44f8fcd741675dfc0b23208cf8",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5800/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7809"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7909"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/e1af8f893da4",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "2f29204de52eb68a2063b9a48c49848fa5988b7b0b49c37e132d771e4b3971a5",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.5",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:05",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "b5d983bc2409105cb3807733e2182ea470bce474fbb52f55d17d52815a5f147d",
                    "EndpointID": "2f29204de52eb68a2063b9a48c49848fa5988b7b0b49c37e132d771e4b3971a5",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.5",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:05",
                    "DriverOpts": null
                }
            }
        }
    }
]

root@HardHome:~# docker logs FileZilla
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing... 
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing... 
[services.d] stopping services
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing... 
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...

**Comment by jlesage** [comment]
Not sure what is the issue.  The container fails to start... If you run:
```
docker run --rm jlesage/filezilla
```
, do you see the container stopping itself?

**Comment by wesmannmsu** [comment]
So, we can close this, it just started working last week,
