### ISSUE TITLE
arm support?

### ISSUE THREAD

**Issue by theniwo** [jlesage/docker-filezilla#12]
Hi, I'd like to install this on arm based machines like raspberry pi and wd mycloud devices. Is there support for arm architecture?

**Comment by jlesage** [comment]
Not yet, but this is something I'm planning to do :)

**Comment by bepece1** [comment]
> Not yet, but this is something I'm planning to do :)

yes!!!! pleaseeeeeeeeee @jlesage

**Comment by ErstBlack** [comment]
Any update on this? @jlesage

**Comment by Kruk79** [comment]
Hi @jlesage
I was wondering if there is any update o this?

**Comment by UktarBelokan** [comment]
Hello, any news for arm support ?

**Comment by jlesage** [comment]
Latest image is now multi-arch.
