### ISSUE TITLE
Filezilla on Openshift

### ISSUE THREAD

**Issue by fedemonte89** [jlesage/docker-filezilla#13]
I'm trying to run jlesage/filezilla image on Openshift, but I'm getting this message:
`s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied`

Image is built from dockerhub image, without particular customization.

Do you how to solve this issue?

Thank's

**Comment by jlesage** [comment]
I'm not really familiar with OpenShift, but looks like the file system permissions are not the expected one.
Can you run something similar to:
```
docker run --rm jlesage/filezilla ls -l /var
```

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
