### ISSUE TITLE
username , password, port

### ISSUE THREAD

**Issue by VLKNKBKSZ** [jlesage/docker-filezilla#14]
Hi, jlesage, i just downloaded the image and made it run with your default docker command. I want to build a spring application that will pull data from the filezilla server. I tried to connect to file filezilla gui but i don't know what the username and password is for this specific host. I tried to add a new server with host: localhost port:5800 and left the username and password emtpy but that didnt work out. How should i connect to the container and upload/download files from the container using the localhost:5800 gui of filezilla? What parameters do i need?
I cannot connect to the ftpserver using host:localhost or 127.0.0.1 username/password empty port:5800(tried also 20 and 21 ) ??

**Comment by jlesage** [comment]
I'm not sure to fully understand the issue, but just to make sure: this container is an FTP *client*, not a server.  Is it what you are looking for?

**Comment by VLKNKBKSZ** [comment]
@jlesage hahahhaah, yeah i found out a couple of hours later that this was a client and not the server. Ended up using delphin ftp server in a docker container. Thanks any how !!

**Comment by jlesage** [comment]
You are welcome!

**Comment by mdkrush** [comment]
What is the credentials for logging into the client?

**Comment by jlesage** [comment]
There is no credentials, unless you configured the container with the `VNC_PASSWORD` environment variable.
