### ISSUE TITLE
Invalid source position for vertical gradient

### ISSUE THREAD

**Issue by EVOTk** [jlesage/docker-filezilla#17]
Hello,

FileZilla docker does not work.
The container starts but cannot access the graphical interface, and I have errors in the logs:

> [...]
> [services.d] starting app...
> [app] starting FileZilla...
> [services.d] done.
> Reading locale option from /config/xdg/config/filezilla/filezilla.xml
> ** (filezilla:910): WARNING **: 01:55:37.036: invalid source position for vertical gradient
> ** (filezilla:910): WARNING **: 01:55:37.036: invalid source position for vertical gradient
> ** (filezilla:910): WARNING **: 01:55:37.039: invalid source position for vertical gradient
> ** (filezilla:910): WARNING **: 01:55:37.039: invalid source position for vertical gradient

I'm on Synology 918+, DSM 6.2.2-5.
Docker Deamon 18.09.6 / Compose 1.24.0

My Container config :
>{
"cap_add" : null,
"cap_drop" : null,
"cmd" : "/init",
"cpu_priority" : 50,
 "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enabled" : false,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "LANG",
         "value" : "en_US.UTF-8"
      },
      {
         "key" : "S6_BEHAVIOUR_IF_STAGE2_FAILS",
         "value" : "3"
      },
      {
         "key" : "S6_SERVICE_DEPS",
         "value" : "1"
      },
      {
         "key" : "USER_ID",
         "value" : "1030"
      },
      {
         "key" : "GROUP_ID",
         "value" : "100"
      },
      {
         "key" : "APP_NAME",
         "value" : "FileZilla"
      },
      {
         "key" : "APP_USER",
         "value" : "app"
      },
      {
         "key" : "XDG_DATA_HOME",
         "value" : "/config/xdg/data"
      },
      {
         "key" : "XDG_CONFIG_HOME",
         "value" : "/config/xdg/config"
      },
      {
         "key" : "XDG_CACHE_HOME",
         "value" : "/config/xdg/cache"
      },
      {
         "key" : "XDG_RUNTIME_DIR",
         "value" : "/tmp/run/user/app"
      },
      {
         "key" : "DISPLAY",
         "value" : ":0"
      },
      {
         "key" : "DISPLAY_WIDTH",
         "value" : "1280"
      },
      {
         "key" : "DISPLAY_HEIGHT",
         "value" : "768"
      },
      {
         "key" : "TZ",
         "value" : "Europe/Paris"
      }
   ],
   "exporting" : false,
   "id" : "fcf260711778f9aae2f82ea5aae61ab30d94604f491679f65b0af1ad0eac150d",
   "image" : "jlesage/filezilla:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "filezilla",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 5800,
         "host_port" : 0,
         "type" : "tcp"
      },
      {
         "container_port" : 5900,
         "host_port" : 0,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/Download",
         "mount_point" : "/data/download",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/filezilla/config",
         "mount_point" : "/config",
         "type" : "rw"
      }
   ]
}

**Comment by jlesage** [comment]
These messages are note related and are "normal".

What issue do you have when you access the UI ?

> {
"container_port" : 5800,
"host_port" : 0,
"type" : "tcp"
},

Did you mapped port 5800 ?

**Comment by EVOTk** [comment]
Hello,
Thx you for reply.

In Synology ""host_port" : 0," = Auto.
I changed 0 (Automatic) to 5800, and it works! Thank you so much.
