### ISSUE TITLE
Configuring reverse proxy for Apache 2

### ISSUE THREAD

**Issue by jpoggi** [jlesage/docker-filezilla#18]
Hi,

First of all, thanks a lot for bringing this nice tool and keeping it up to date, very usefull.

I've just a little problem completing the reverse proxy configuration on Apache 2 to access it throught TLS.

Here's my virtualhost configuration (I've hide some variables):

```
<VirtualHost *:80>
        Define SERVER_NAME filezilla.domain.tld
        ServerName ${SERVER_NAME}

        RewriteEngine On
        RewriteCond %{SERVER_NAME} =${SERVER_NAME}
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

        CustomLog ${APACHE_LOG_DIR}/${SERVER_NAME}_access.log combined
        ErrorLog ${APACHE_LOG_DIR}/${SERVER_NAME}_error.log
</VirtualHost>

<VirtualHost *:443>
        ProxyRequests Off
        ProxyPreserveHost On

        ServerName ${SERVER_NAME}
        SSLProxyEngine On

        ProxyPass /websockify ws://filezilla.domain.tld/
        ProxyPassReverse /websockify http://filezilla.domain.tld/

        ProxyPass / http://localhost:5800/
        ProxyPassReverse / http://localhost:5800/

        RequestHeader set X-Forwarded-Proto "https"

        SSLEngine On
        SSLCertificateFile /etc/apache2/certs/live/domain.tld/fullchain.pem
        SSLCertificateKeyFile /etc/apache2/certs/live/domain.tld/privkey.pem

        CustomLog ${APACHE_LOG_DIR}/${SERVER_NAME}_access.log combined
        ErrorLog ${APACHE_LOG_DIR}/${SERVER_NAME}_error.log
</VirtualHost>
```

I've load module 'proxy_wstunnel' and I've no error in the Apache logs, the only error I've got is from my browser in console mode:

```
WebSocket connection to 'wss://filezilla.domain.tld/websockify' failed: Error during WebSocket handshake: Unexpected response code: 301
WebSocket on-error event
Msg: Server disconnected (code: 1006)
```

Any ideas to correct this ?

FYI I can access the container GUI through classic port without reverse proxy in front of it.

Regards.

**Comment by jpoggi** [comment]
Hi @jlesage,

Any idea ?

**Comment by jlesage** [comment]
Sorry for the delay on this.  I'm not really familiar with Apache config...  However, you could look at logs under `log/nginx/`, under the directory you mapped to `/config`.  You can see if the requests are reaching the container and if yes, if they are correct/expected...

**Comment by jpoggi** [comment]
Hi,

No problem for the delay, thanks for the tip, I'll take a look into ~/config/log/nginx.

Keep you in touch.

**Comment by jpoggi** [comment]
No more informations on this logs...

I'll keep searching on my own, if I find the solution, I will come back to share it.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
