### ISSUE TITLE
Cannot run command after transfer queue finishes

### ISSUE THREAD

**Issue by terminalwhoami** [jlesage/docker-filezilla#19]
If you right click in the white space where the transfer queue is located, there is an option for 'action after queue completion' and then 'run command'.

Depending on the syntax of what is placed in the 'run command' box, results in either "Permission Denied" or "execvp(<command>) failed with error 2!

Both scripts and simple commands, like touch, fail.

I've verified that the file system that the docker is running from does not have the noexec flag on it.  I've also checked permissions of the folder and the scripts and that hasn't made a difference.

**Comment by jlesage** [comment]
Which command did you try exactly?  I tried `touch /config/test-finish` and it worked well.

**Comment by terminalwhoami** [comment]
I've tried:
touch test.txt
touch "text.txt"
"touch test.txt"

and then i made a two line script, hello.sh
```
#!/bin/bash
touch hello.txt
```

and put it in the command box a few different ways:
./hello.sh
hello.sh
/storage/.hello.sh
./storage/hello.sh

**Comment by terminalwhoami** [comment]
I was mainly using touch as an easier command for debugging to figure out whats going on.  My eventual goal is to either run

unrar e -r *.rar on /storage/ or a small script that contains that unrar command and more in the same /storage/ directory

**Comment by jlesage** [comment]
Ok, then invoking a script like this should work:
```
/storage/hello.sh
```

However, note that `unrar` is not part of the image.

**Comment by terminalwhoami** [comment]
/storage/hello.sh was one of the options I tried, and that results in execvp(/storage/hello.sh) failed with error 2!

**Comment by terminalwhoami** [comment]
got the script calling to work, Filezilla needed the command to be

`sh "storage/hello.sh"`

so now I just need unrar.  Is that something only you can do by updating the image to include unrar, or can that be passed into the docker somehow?  its located at /usr/bin/unrar

**Comment by jlesage** [comment]
I just realized that you script is starting with `#!/bin/bash`.  It should start with `#!/bin/sh`, since `bash` is not part of the image.

For unrar, you could install it by running `docker exec <container name> add-pkg unrar`.  But note that with this method, you will have to re-install unrar if you re-create the container.  A more robust method would be for me to add support for installing custom packages via an environment variable.

**Comment by terminalwhoami** [comment]
ah that fixed it, now I can just write the path to the script.

and the docker exec command seems to have done the trick!

Final question, is there a way to add the docker exec command into the docker config file so that if I ever re-create the docker, it'll do it automatically? I'm using portainer.

**Comment by jlesage** [comment]
I'm not sure this can be done in portainer...
I will try to update the image this weekend to support installation custom packages via an environment variable.

**Comment by terminalwhoami** [comment]
Can it be done with other docker management systems? I've been trying to search for variations on automating docker exec commands and my search skills are failing me.

obviously your solution of adding it to the image is better, but now i'm curious to see if it can be done.

**Comment by terminalwhoami** [comment]
maybe you can help me with this as well, its another bash vs sh issue.  The script that i want to run on completion has a `mv **/*.<filetype>`. it works in my regular terminal because i can do `shopt -s globstar` to [update the bash setting](https://www.linuxjournal.com/content/globstar-new-bash-globbing-option) for **.

I'm using `mv **/*.<filetype>` to move all the files of a certain type that get downloaded by filezilla, whether they're in the directory or in a sub directory.  Since I can't use bash, that line in my script only gets the files in the sub directories and not the current directory.  Is there a different syntax I can use with mv to get all the <filetype> in the directory and its subdirectories?

**Comment by jlesage** [comment]
> Can it be done with other docker management systems? I've been trying to search for variations on automating docker exec commands and my search skills are failing me.

To my knowledge there is no single command that allows to create the container and execute a command inside it.

> obviously your solution of adding it to the image is better

If you update to the latest image, you will be able to use the `INSTALL_EXTRA_PKGS` variable to install your package.

**Comment by jlesage** [comment]
When you move you files, do you want them to end up in the same destination directory, without their subfolder ?  If yes, you could use the `find` command:
```
find <directory where you files are> -type f -name "*.<filetype>" -exec mv {} <destination folder> ';'
```

Example:
```
find /downloads -type f -name "*.txt" -exec mv {} /output/ ';'
```

**Comment by terminalwhoami** [comment]
> If you update to the latest image, you will be able to use the `INSTALL_EXTRA_PKGS` variable to install your package.

How do I verify that I'm running the latest image?  For variable usage, do I just type in 'unrar'?

**Comment by terminalwhoami** [comment]
Portainer says org.label-schema.version | 1.23.1 and my unrar script seems to be working

Is there a way to control click different lines when accessing file zilla via a web browser to select what you want to download?  If I control click, it gets treated as a right click.  Havent found a combination of keyboard modifiers that seems to consistently work.

**Comment by jlesage** [comment]
Ctrl+click is working for me.  Which browser are you using ?  Do you have any keyboard shortcut assigned to ctrl+click ?

**Comment by terminalwhoami** [comment]
Firefox is my browser of choice, tried on both Mac and Windows.  Just tested it on chrome, and no issue.  So I guess its either firefox or possibly an extension I have on firefox.  I'll do some more testing and report back.

**Comment by terminalwhoami** [comment]
update: works on firefox on windows and chrome on mac, but firefox on mac does not work, even with all add-ons disabled.

It seems that ctrl+click on a mac is right click system wide, but there doesn't seem to be a way to disable that.  Not sure why Chrome "ignores" and lets me use it the way I want in the filezilla docker.  I tried command + click on the docker on a mac while in firefox, and that didn't work.  Tried a few different key combos and trying left ctrl vs right ctrl, no luck.

**Comment by jlesage** [comment]
For me it's working on Mac with Safari.  So maybe it's something specific to Firefox on Mac ?

**Comment by terminalwhoami** [comment]
possibly, i have the same results as you on safari.  Can you test firefox on mac?

**Comment by jlesage** [comment]
I have the same behaviour as you for Firefox on Mac: ctrl+click is doing a right click.

**Comment by terminalwhoami** [comment]
dang, well i guess i'll just have to use chrome or safari for filezilla.  that's a shame.
