### ISSUE TITLE
App Layout

### ISSUE THREAD

**Issue by C4Wiz** [jlesage/docker-filezilla#2]
window positions (layout) are not remembered when app is restarted

**Comment by jlesage** [comment]
Did you updated the image?  This has been fixed recently.

**Comment by C4Wiz** [comment]
Yep on latest

David Smythe
Sent from my  iPhone 7 Plus on iOS 10

On Aug 3, 2017, at 10:15 AM, Jocelyn Le Sage <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you updated the image? This has been fixed recently.

**Comment by jlesage** [comment]
So what is not working exactly?

**Comment by C4Wiz** [comment]
when i start the container it looks like this:

![screen shot 2017-08-03 at 1 23 06 pm](https://user-images.githubusercontent.com/3883521/28939670-4bbc98f4-784f-11e7-9489-de3e31e19752.png)

and after i adjust everything to the way i like it:

![screen shot 2017-08-03 at 1 25 15 pm](https://user-images.githubusercontent.com/3883521/28939686-5d27285c-784f-11e7-8eb6-8aa4b656b72e.png)


then after the container is stopped then started all is lost and it's back to the first picture

**Comment by C4Wiz** [comment]
i left the app window open and stopped and started the docker and the settings remained!

**Comment by jlesage** [comment]
What you did differently?

**Comment by C4Wiz** [comment]
i left the app window open and stopped and started the docker and the settings remained!

**Comment by jlesage** [comment]
Ok but when it was not working, what you were doing differently?

**Comment by C4Wiz** [comment]
closing the app window, then stopping the docker container

**Comment by jlesage** [comment]
Ok.  When you close FileZilla yourself (File->Exit), the container is also stopping itself.  Maybe that also stopping the container manually was preventing execution of the shutdown routine.

It seems that we can close the issue.
