### ISSUE TITLE
SFTP / FTPS / FTP connection failed

### ISSUE THREAD

**Issue by Artmorse** [jlesage/docker-filezilla#20]
Hi,

I have detected 3 problems but I can't fix them.

1. When I tried to establish a FTP or FTPS connection I have this error that occurs.
```
Status:	Connecting to XX.XX.XX.XX:XXXX...
Error:	Connection timed out after 20 seconds of inactivity
Error:	Could not connect to server
```

2. When I tried to establish a SFTP connection I have this error that occurs.
```
Error:	ssh_init: Try again
Error:	Could not connect to server
```

3. With some domain names the resolution fails and this error occurs.
```
Status:	Resolving address of XXXXXX.XXX
Status:	Connection attempt failed with "EAI_AGAIN - Temporary failure in name resolution".
Error:	Could not connect to server
```

I have installed the Docker Image on my Synology. 
The user is defined by `USER_ID` and `GROUP_ID` variables, is an administrator. 
I access to the UI with a Reverse Proxy, in HTTPS.

I have done these tests on the Docker Image and simultaneously with the "real" Filezilla application.

**Comment by jlesage** [comment]
Can you share the network settings you did for this container ?

**Comment by Artmorse** [comment]
Yes this is my _Ports Parameters_.

![Screenshot_2020-05-24_17-44-20](https://user-images.githubusercontent.com/24521660/82758342-3ececa80-9de6-11ea-81f7-b285ab698e01.png)

I don't have any redirection with my router (except for the Reverse Proxy : port n°443).

I have tried to turn on the parameter "Execute the container with the help of elevated parameters." but it didn't succeed.
I have tried to change my port with the default configuration but it didn't succeed.
I haven't tried yet to redirect the port n°50900 (NAS) with the port 5900 of my router (but I am not sure that that is the problem)

**Comment by jlesage** [comment]
Can you provide the output of `docker inspect <container name>` ?

Do you have the firewall turned on ?  If yes, does disabling it fixes the issues ?  Looks like the container if not able to communicate with anything.

**Comment by Artmorse** [comment]
Yes, when the firewall turned off it's works.

**Comment by jlesage** [comment]
Ok, then the issue is not related to the container itself: your firewall seems incorrectly configured (i.e it blocks your outgoing FTP traffic).

**Comment by Artmorse** [comment]
I've tried to open the port n°21 but without success...
I'll retry in 2 hours!

What are the port which need to be opened ?

(I've change my default SSH port, is this a source of problem?)

**Comment by jlesage** [comment]
FTP is using port 21 for the initial connection and then use a dynamic port for transfers.
Do you really need to block outgoing connections ?

**Comment by Artmorse** [comment]
I can't choose if the connection are outgoing or ingoing.
Or I don't what how do that ?

**Comment by Artmorse** [comment]
It works!
I had forgot a route in my firewall...

Thanks for your time!
(Now i can install your others docker images!)
