### ISSUE TITLE
once downloaded files not accessibles

### ISSUE THREAD

**Issue by stephcar75020** [jlesage/docker-filezilla#22]
Hi 
first of all i'm a newbie ...
fillezilla docker installed and running but when i download a file the file is in my download folder but when i try to access the file (video file) from a windows pc , i see the file but impossible to play the file or evec copy it 
what i've done wrong ?

thank you

**Comment by jlesage** [comment]
So I assume that your download folder is shared over the network ?  Or you are running Docker in Windows ?
Do you have other files in your download folder that works ? If yes, you could compare their ownership/permissions with the ones of downloaded files.

**Comment by stephcar75020** [comment]
Hello 
yes it's a shared folder over the network, i'm running docker on a debian machine running openmedia vault but i want to access theses files from a windows computer, by the way event if i want to access the downloaded files (with filezilla) from another docker app (PLEX) it doesn't work too 
i will check the ownership/permission 

Happy New Year from Paris !

**Comment by jlesage** [comment]
So if you SSH to your Debian machine, you can look at the files permissions with `ls -l /path/to/your/folder`.
For your Plex container, did you configure any user/group id ?  If yes, maybe you need to adjust `USER_ID` and `GROUP_ID` variables for FileZilla as well ?

Bonne année à vous aussi :)

**Comment by stephcar75020** [comment]
i will check the permissions
concerning the user/group id i use the same on Filezilla and Plex container

**Comment by stephcar75020** [comment]
After checked it seems to be a permission problem
what it's strange for me is :
downloading from the same ftp the same file
in sftp the file is not accessible
in regular ftp file is accessible

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
