### ISSUE TITLE
fzsftp could not be started

### ISSUE THREAD

**Issue by zorrax2b** [jlesage/docker-filezilla#27]
Hello
filezilla installation was fine and filezilla works well with classic ftp connection
but the sftp mode seems not working
'fzsftp could not be started"
is there a way to work with sftp ??
I have tested another docker image and it worked but I prefered your interface
thanks

**Comment by jlesage** [comment]
Do you have the issue with all servers ?  I tried with one from https://www.sftp.net/public-online-sftp-servers and it connected successfully.

**Comment by zorrax2b** [comment]
for all of free sftp server I got the same answer "fzsftp could not be started"

**Comment by zorrax2b** [comment]
may be one thing:
I tried to change some parameters and for "logging" I get this error: 
" /run/s6/services/app/
No such file or directory"
maybe something wrong in configuration

**Comment by jlesage** [comment]
To get a complete picture of your container's environment, can you share the output of:

```
docker inspect <container name>
```

**Comment by rwolfcastle1** [comment]
I'm having the exact same issue with SFTP. I've spent far too long trying to figure it out. I found a reference for a Mac here (https://forum.filezilla-project.org/viewtopic.php?t=6974) but I don't fully understand the inner-workings of docker to figure out if it's a similar issue.

**Comment by zorrax2b** [comment]
sorry for the delay (vacation)
below the output of docker inspect:
`docker inspect jlesage-filezilla1
[
    {
        "Id": "a63668d202a6b366bb22901dcac0cde8ffa9ef95afe1611013c75c99669ebf08",
        "Created": "2021-08-03T21:01:06.197913148Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-08-05T15:07:57.863819276Z",
            "FinishedAt": "2021-08-05T20:12:45.726539303Z",
            "StartedTs": 1628176077,
            "FinishedTs": 1628194365
        },
        "Image": "sha256:ca976317c4f4ed80f07b7cba8fc0c691a0eaed4f69351454b606134bfdd23282",
        "ResolvConfPath": "/volume1/@docker/containers/a63668d202a6b366bb22901dcac0cde8ffa9ef95afe1611013c75c99669ebf08/resolv.conf",
        "HostnamePath": "/volume1/@docker/containers/a63668d202a6b366bb22901dcac0cde8ffa9ef95afe1611013c75c99669ebf08/hostname",
        "HostsPath": "/volume1/@docker/containers/a63668d202a6b366bb22901dcac0cde8ffa9ef95afe1611013c75c99669ebf08/hosts",
        "LogPath": "/volume1/@docker/containers/a63668d202a6b366bb22901dcac0cde8ffa9ef95afe1611013c75c99669ebf08/log.db",
        "Name": "/jlesage-filezilla1",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/volume1/docker/filezilla/data:/transfert:rw",
                "/volume1/docker/fz2:/config:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "db",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5800"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5900"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "USER_ID=1031",
                "GROUP_ID=65538",
                "APP_NAME=FileZilla",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768"
            ],
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 50,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/volume1/docker/filezilla/data",
                "Destination": "/transfert",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/volume1/docker/fz2",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "ba226a451b7e6019431a0a13095d346f1537fb91dc80fd24cf2f8a8362f0efc1",
                "Source": "/volume1/@docker/volumes/ba226a451b7e6019431a0a13095d346f1537fb91dc80fd24cf2f8a8362f0efc1/_data",
                "Destination": "/storage",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "jlesage-filezilla1",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "USER_ID=1031",
                "GROUP_ID=65538",
                "APP_NAME=FileZilla",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768"
            ],
            "Cmd": [
                "/init"
            ],
            "Image": "jlesage/filezilla:latest",
            "Volumes": {
                "/config": {},
                "/storage": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.description": "Docker container for FileZilla",
                "org.label-schema.name": "filezilla",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-filezilla",
                "org.label-schema.version": "1.32.0",
                "org.opencontainers.image.created": "2021-07-13T22:19:31Z",
                "org.opencontainers.image.revision": "d9c72894803656fb074531bf2945293c8c2fd17c",
                "org.opencontainers.image.source": "https://github.com/jlesage/docker-filezilla.git",
                "org.opencontainers.image.url": "https://github.com/jlesage/docker-filezilla"
            },
            "DDSM": false
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b40b1007311f01e82fd488c5b77f5a3433223a6e97d4893f94d64d0c9f482b8d",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/b40b1007311f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "af62d1410f36d369a4bf644b776c9b05a30fb1e63c750aafab0691e82db50913",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
`

**Comment by freezoom1** [comment]
@zorrax2b I also have the same issue after going from FTP to SFTP with this image/ container. Running this on a synology diskstation 

I have confirmed that i can SFTP into the remote server using two other machines without issue. To add to this I suspect this isn't the only image with this problem. Please see [ linuxserverdockerFZ](https://github.com/linuxserver/docker-filezilla) with a different gui, but same failure *fzsftp failed to start* 

Hopefully bumping this we can get a little more traction and solve the issue for that repo as well

**Comment by jlesage** [comment]
This is an interesting finding.   Maybe you should try to report the issue on the official FileZilla forum: https://forum.filezilla-project.org

**Comment by freezoom1** [comment]
> @zorrax2b I also have the same issue after going from FTP to SFTP with this image/ container. Running this on a synology diskstation
> 
> I have confirmed that i can SFTP into the remote server using two other machines without issue. To add to this I suspect this isn't the only image with this problem. Please see [ linuxserverdockerFZ](https://github.com/linuxserver/docker-filezilla) with a different gui, but same failure _fzsftp failed to start_
> 
> Hopefully bumping this we can get a little more traction and solve the issue for that repo as well

@jlesage  I wanted to give an update. After putting some careful consideration together on my troubleshooting here's where I'm at, I wanted to get this out ASAP in case anyone reads this, they can hopefully cut down troubleshooting. 

What have I done: 

- Tested sftp from the docker container via CLI == SUCCESS 
- Tested SFTP connection from Filezilla gui == FAILURE        _fzsftp failed to start_
- On another system (debian and MacOS both) , tested same version of Filzezilla w/ SFTP to server == SUCCESS 
- On macOS ran this docker image (jlessage/docker-filezilla) connected via SFTP to remove server == SUCCESS 


At this point, I assume there is some problem with configuration, permissions or ports on my Synology Diskstation NAS which is giving the error. What is strange to me is that the cmd line SFTP works from the docker image, but the gui version of filezilla does not.

**Comment by mog54** [comment]
> > @zorrax2b I also have the same issue after going from FTP to SFTP with this image/ container. Running this on a synology diskstation
> > I have confirmed that i can SFTP into the remote server using two other machines without issue. To add to this I suspect this isn't the only image with this problem. Please see [ linuxserverdockerFZ](https://github.com/linuxserver/docker-filezilla) with a different gui, but same failure _fzsftp failed to start_
> > Hopefully bumping this we can get a little more traction and solve the issue for that repo as well
> 
> @jlesage I wanted to give an update. After putting some careful consideration together on my troubleshooting here's where I'm at, I wanted to get this out ASAP in case anyone reads this, they can hopefully cut down troubleshooting.
> 
> What have I done:
> 
> * Tested sftp from the docker container via CLI == SUCCESS
> * Tested SFTP connection from Filezilla gui == FAILURE        _fzsftp failed to start_
> * On another system (debian and MacOS both) , tested same version of Filzezilla w/ SFTP to server == SUCCESS
> * On macOS ran this docker image (jlessage/docker-filezilla) connected via SFTP to remove server == SUCCESS
> 
> At this point, I assume there is some problem with configuration, permissions or ports on my Synology Diskstation NAS which is giving the error. What is strange to me is that the cmd line SFTP works from the docker image, but the gui version of filezilla does not. & **To clarify, at this point, I do not think this error has to do with the image or container.**

Hello, i have the same issue, did you find a solution ?

Thanks

**Comment by jlesage** [comment]
A new Docker image has been released.  Maybe you can check if you see the problem with it.

**Comment by mog54** [comment]
> A new Docker image has been released. Maybe you can check if you see the problem with it.

Hello, same with the new release :/

**Comment by jlesage** [comment]
Can you share a server with which you have the problem ?
Currently I cannot reproduce myself.

**Comment by mog54** [comment]
> Can you share a server with which you have the problem ? Currently I cannot reproduce myself.

It's on my home synology, so it's a bit complicated.

i will try docker on a linux serveur

**Comment by MartinHotmann** [comment]
Indeed I am now also facing this exact same issue.
I, for security reasons switched to SFTP and get the very same error.

"fzsftp could not be started".

I took a little closer look inside the container as the error was not very usefull.
Inside the container the fzsftp file is under `/usr/bin/fzsftp`, is executable and is owned by root.

When executing it, I get this:

```
$ /usr/bin/fzsftp
0fzSftp started, protocol_version=11
```

Which is the same as if I would have executed the `C:\Program Files\FileZilla FTP Client\fzsftp.exe` on windows.

On Windows (latest FZ Version) it works and on docker (latest FZ version) it does not. I also can connect to the very same server with my windows FZ, but not the dockerized one.

Maybe fzsftp was moved somewhere and therefore is not executable under the old path? Does someone know what the expected path for fzsftp is?

@jlesage may this helps. May not .. :P

**Comment by MartinHotmann** [comment]
Maybe this helps debugging. I found the section of the source code which is responsible for this error:
https://svn.filezilla-project.org/filezilla/FileZilla3/trunk/src/engine/sftp/connect.cpp?revision=10602&view=markup#l203

**Comment by MartinHotmann** [comment]
Full debug log:

```
08:16:37	Trace:	CControlSocket::SendNextCommand()
08:16:37	Trace:	CSftpConnectOpData::Send() in state 0
08:16:37	Status:	Verbinde mit server.domain.tld...
08:16:37	Trace:	Going to execute /usr/bin/fzsftp
08:16:37	Trace:	Could not create shm_fd_
08:16:37	Trace:	CControlSocket::DoClose(66)
08:16:37	Trace:	CControlSocket::ResetOperation(66)
08:16:37	Trace:	CSftpConnectOpData::Reset(66) in state 0
08:16:37	Fehler:	fzsftp konnte nicht gestartet werden
08:16:37	Fehler:	Herstellen der Verbindung zum Server fehlgeschlagen
08:16:37	Trace:	CFileZillaEnginePrivate::ResetOperation(66)
08:16:37	Status:	Nächsten Versuch abwarten...
08:16:42	Trace:	CControlSocket::DoClose(66)
08:16:42	Trace:	CControlSocket::ResetOperation(66)
08:16:42	Trace:	CFileZillaEnginePrivate::ResetOperation(66)
08:16:42	Trace:	CControlSocket::DoClose(66)
08:16:42	Trace:	CControlSocket::ResetOperation(66)
08:16:42	Trace:	CFileZillaEnginePrivate::ResetOperation(66)
```

**Comment by MartinHotmann** [comment]
Did some testing and had a talk over here: https://trac.filezilla-project.org/ticket/12688#comment:9 with the dev of FZ.

1. probably the kernel version of the hostOS is important and relevant.
1.1. I use a Syno and am on kernel version `3.10.108` Please always post kernel versions from now on (`uname -r`)
2. also relevant is the FZ version or libFZ versin.
2.1. since v1.29.0 this docker is _broken_ for me. At least the SFTP functionality - rest still works.

I tested a lot of versions and tried to go as low as possible to find a tag which works and then upped it always untill it broke.

[v1.29.0](https://github.com/jlesage/docker-filezilla/releases/tag/v1.29.0) breaks SFTP for me and [v1.28.0](https://github.com/jlesage/docker-filezilla/releases/tag/v1.28.0) still works with SFTP. So for all that want to use SFTP immediately just switch down to [v1.28.0](https://github.com/jlesage/docker-filezilla/releases/tag/v1.28.0) and use SFTP. It is not very up to date but works better than the new versions and is still compatible with older kernels.

I tested PasswordAuthentication and Private_Key Authentication. both work.

Lets see if the dev (not @jlesage, but the dev of FZ direct) can make a new version with a better compatibility or if we (with older kernels) just have to use outdated versions :)

**Comment by jlesage** [comment]
Thanks for the info.  After reviewing all this, I think the issue is related to usage of the `memfd_create()` system call.  This system call exists since kernel version 3.17, thus explaining why it's not working on Synology.

I see from FileZilla sources that usage of this system call is optional: an alternative method is used when compiled on a machine that doesn't not support this system call.

So I will try to forcefully disable usage of `memfd_create()` during the compilation of FileZilla and provide a new image.  This will hopefully fixes your issue.

**Comment by MartinHotmann** [comment]
Man that would be super awesome! But on the other hand I don't want to "downgrade" the Image itself for others, just because I (and some others) have that situation, but that really would be cool.

Maybe you can release these docker images which are backwards compatible under a different tag like "backport" so people can choose which one they want. If it works fine for them they can use the normal one, if they run into this problem they shall use the backport :)

Ping me if you have something to test.

**Comment by jlesage** [comment]
I would not consider this as a downgrade, but as another way to do the same thing.

I new image is available.  Let me know how if it is better.

**Comment by MartinHotmann** [comment]
It works! Nice, that means I can use this even with my old Kernel version.

Are there any negative effect by "doing the same thing the other way" for other people which have newer Kernels?

**Comment by jlesage** [comment]
Nice this see that it's working.

I'm not the developer of FileZilla, but I don't think there is negative effects (I don't see them).  You can see in the code what is done when `memfd_create` is not supported: https://svn.filezilla-project.org/filezilla/FileZilla3/trunk/src/engine/sftp/connect.cpp?view=markup#l73
