### ISSUE TITLE
Cant "trust connection"

### ISSUE THREAD

**Issue by MartinHotmann** [jlesage/docker-filezilla#28]
I installed docker and tried to connect to a server, it works but I somehow cant trust the connection, even when the SSL Cert is valid.
Transfering Data works. But "Trust this connection is greyed out.
![FileZilla Problem](https://user-images.githubusercontent.com/17692860/146599835-ae002835-2208-484c-82b7-8316b602af1e.png)

Is there a workaround or an explanation for this?
I have set the correct "TZ" settings as env in docker-compose.yml.

Thanks in advance!

**Comment by jlesage** [comment]
It seems that the check boxes are greyed out when the certificate is invalid or expired.  Did you check that all certificates in the chain are also valid ?

I tried a test FTP server (see https://test.rebex.net) and the checkboxes were not greyed out.  Can you also try this server to if you have the same issue ?

**Comment by MartinHotmann** [comment]
Thank you for you response!

> Did you check that all certificates in the chain are also valid ?
Yes I did. When I connect from every other FileZilla instance (on Windows, Linux which is not dockerized) then everything works perfectly fine. Never had this issue. Also the cert is valid from:
2021 Okt. 20 - 2022 Jan. 18

> I tried a test FTP server (see https://test.rebex.net) and the checkboxes were not greyed out. Can you also try this server to if you have the same issue ?
I will do so and report back. Thanks in advance!

**Comment by MartinHotmann** [comment]
Ok here the update:

> I tried a test FTP server (see https://test.rebex.net) and the checkboxes were not greyed out. Can you also try this server to if you have the same issue ?

Thanks, with this it works perfectly fine. 

Here some more information on the issue:
FileZilla (docker) reports the root CA cert is not valid anymore. But when I connect with any other FileZilla instance to my server it works perfectly, while it does not work with the docker version. Also this docker version reports a SSL Cert (CA) which is not valide anymore which I cant even inspect on all other instances. I just see :

- Cert
- chain Cert

but the docker versin reports 4 instances:

- Cert
- chain Cert
- chain Cert 2
- root Cert

Dont know why this just occurs on the docker version.

**Comment by jlesage** [comment]
What is the reason why the root CA is not valid ?

**Comment by MartinHotmann** [comment]
FileZilla (docker) states it is outdated. But other FileZilla instances do not show this.

**Comment by jlesage** [comment]
It seems that the issue is related to this: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

Which version is your other FileZilla instance that works ?   Is it also on Linux  ?

**Comment by MartinHotmann** [comment]
> It seems that the issue is related to this: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

True .. thats is matching my CA Cert, thanks for pointing out.

> Which version is your other FileZilla instance that works ?
Latest v3.57.0 (installed through Chocolatey)

> Is it also on Linux ?
Tested it on linux (debian) a week ago (also latest, whatever version it was then) but dont have this system anymore.

**Comment by jlesage** [comment]
Can you try the latest Docker image to see if you still have the problem ?

**Comment by MartinHotmann** [comment]
> Can you try the latest Docker image to see if you still have the problem ?

Thank you very much, updating the container to its latest version actually solved the problem. The session immediately could be saved and was trusted in forst place!
