### ISSUE TITLE
Can there be a mobile friendly UI as well? 

### ISSUE THREAD

**Issue by milindhg** [jlesage/docker-filezilla#29]
Thanks a lot for this repo. This was exactly what I was looking for on my home docker server and control it remotely from anywhere. 👍🏻 
When I tried to open the Filezilla docker URL in a mobile browser, it does get rendered good enough. However, the UI box is very small to operate properly. Are there any plans on making the UI Mobile browser friendly as well? It will be so much easier to operate on a mobile device.

**Comment by jlesage** [comment]
Web access is already mobile friendly.  However, note that you are accessing a desktop app: FileZilla itself is not a mobile-friendly application.
You may want to provide a screenshot so I better understand what you mean by "the UI box is very small".

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
