### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by C4Wiz** [jlesage/docker-filezilla#3]
i recieve this everytime i start the filezilla docker and connect to the webgui:

![screen shot 2017-08-22 at 4 46 45 pm](https://user-images.githubusercontent.com/3883521/29590985-dad815f4-8759-11e7-8d70-d8d40fa804c1.png)

**Comment by jlesage** [comment]
Thanks for reporting.  Seems to be an issue with the latest FileZilla version: https://forum.filezilla-project.org/viewtopic.php?t=45948

**Comment by jlesage** [comment]
Fixed in v1.3.3.
