### ISSUE TITLE
General request for ALL of your VNC docker

### ISSUE THREAD

**Issue by MartinHotmann** [jlesage/docker-filezilla#31]
This is a general request, but I will post it here, since it wouldn't matter where I post it.

The request is very short: beeing able to define VNC port with Enviroment variable instead of docker portmapping.

Why? If you want to pipe a docker through a VPN which is a docker itself you will need to remove ALL portmappings from the target container and put them into the VPN container. But if two portmappings now have the same target port (5800) it will not work for both target containers.

### Example
1. VPN docker called "vpn"
2. `jlesage/docker-firefox` called "firefox"
3. `jlesage/docker-filezilla` called "filezilla"

Container `#3` & `#2` should be piped through the `#1` since they should just be accessing the internet via VPN. For doing this you need to remove ALL portmappings from the target container (`#3` & `#2`) and define the network like this:
`network_mode: "container:vpn"` in the `docker-compose.yml` (this does not work if target container (`#3` & `#2`) do have portmappings)

No portmappings means: both of them fall back to their native internal port (5800).
But if both are using this port how can you define two ports at the VPN container to proxy them to one single port. This will create a racecondition. The first of the two target containers which bootet up will get the port, the other will not be reachable through VNC on the wanted port.

Therefore there is a need to be able to define an internal port which this container is listening to natively. I would appreciate a Environment Variable called "`PORT`" which would set the VNC port statically to its value. If PORT is set, portmappings should still work, but they dont have to anymore since you can choose the port.

Maybe two new Env variables should be introduces:
1. `PORT_WEB` (default or when unset is "5800")
2. `PORT_VNC` (default or when unset is "5900")

Hope its understandable. If not I am more then willing to explain it in different words.

Thanks!

**Comment by jlesage** [comment]
Yes, this is something planned that will be soon possible.

**Comment by jlesage** [comment]
This is now supported with latest image.
