### ISSUE TITLE
Server disconnected (code: 1006)

### ISSUE THREAD

**Issue by hidvegin** [jlesage/docker-filezilla#34]
I have got a Synology DS218+ with Intel processor and 2 GB DDR3 RAM. I use docker with your FileZilla container. I can access the GUI on 5800 port but I got this error every time: Server disconnected (code: 1006). But If I refresh the webpage I got back again the GUI, after several minutes I got the same error again. What should I do with this error? I attached a picture about the error:
<img width="1440" alt="Screenshot 2022-02-01 at 21 25 44" src="https://user-images.githubusercontent.com/52884076/152045693-d8b6c75c-e628-43df-b8d4-41d10866423a.png">

**Comment by luzkenin** [comment]
I too have this issue. Tried switching back to 1.33 but no luck.

**Comment by jlesage** [comment]
Did you try to clear your browser's cache?

**Comment by luzkenin** [comment]
It does seem to be the browser (Firefox) as it works fine in Edge. Thanks.

**Comment by wastingaeons** [comment]
fwiw, this happens to me when using it behind a web proxy and/or cloudflare. accessing it directly, it stays up.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
