### ISSUE TITLE
Deleting files or refreshing the folder/file list resets the local view back to the /storage folder

### ISSUE THREAD

**Issue by bjsswanson** [jlesage/docker-filezilla#35]
Whenever I delete a file/folder or refresh the file/folder view it reloads the local directory view back to /storage.

The remote directory refreshes successfully and stays in the current folder:

It doesn't seem related to the "Default local directory" in the Advanced settings as changing this still reverts the view to /storage even when the value is a different folder (e.g. / )

**Comment by jlesage** [comment]
Do you see the same behaviour with the latest version ?  I don't seem to reproduce on my side.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
