### ISSUE TITLE
Update v3.60.00 + dependencies

### ISSUE THREAD

**Issue by MartinHotmann** [jlesage/docker-filezilla#36]
Update v3.60.00 is available, as also some other dependencie updates:

Available updates for [HERE](https://github.com/jlesage/docker-filezilla/blob/master/Dockerfile#L14-L16):

```
ARG LIBFILEZILLA_VERSION=0.37.2
ARG FILEZILLA_VERSION=3.60.0
ARG VIM_VERSION=8.2.5037
```

Somehow the docker version and the Windows version are not based on the same dependencies. They don't have to, but maybe there is a way to update these dependencies since running on old software is never good :)

Windows v3.60.00:
![image](https://user-images.githubusercontent.com/17692860/170854505-d35065a8-37ec-4879-9c51-f6487c49d71d.png)
wxWidgets: 3.0.6
GnuTLS: 3.7.2
SQLite: 3.35.5

Docker v3.59.00:
![image](https://user-images.githubusercontent.com/17692860/170854530-c9d45466-e5bf-4307-ba4e-d0107c742a56.png)
wxWidgets: 3.0.4
GnuTLS: 3.7.1
SQLite: 3.36.0

I honestly don't know if there is a way to define of influence these versions directly, and if, if it is possible with these given parameters or if something extra is required, but would be cool to have all and everything up to date.

Thanks in advance!

**Comment by MartinHotmann** [comment]
Here some handy commands to automatically get always the latest version :)

LIBFILEZILLA_VERSION:
```
curl -s https://download.filezilla-project.org/libfilezilla/ | grep ".tar.bz2" | tail -n 1 | sed -n 's/.*-\([0-9].[0-9][0-9].[0-9]*\).*/\1/p'
```

FILEZILLA_VERSION:
```
curl -s https://download.filezilla-project.org/client/ | grep "_src.tar.bz2" | tail -n 1 | sed -n 's/.*_\([0-9].[0-9][0-9].[0-9]*\).*/\1/p'
```

VIM_VERSION
```
curl -s https://api.github.com/repos/vim/vim/tags | grep "name" | head -1 | sed -n 's/.*v\([0-9]*.[0-9]*.[0-9]*\).*/\1/p'
```

VIM_TAR_DIRECT_DOWNLOAD_URL:
```
curl -s https://api.github.com/repos/vim/vim/tags | grep "tarball_url" | head -1 | cut -d '"' -f 4
```

Hope that helps setting the versions to the always newest version more easy :)
Maybe even like this:

set version to automatically detected URL and if not available fallback to hardcoded version number.

**Comment by MartinHotmann** [comment]
Ah I see, that makes sense. Thanks for the detailed explanation.

I hope you anyway can use the code-snippets to quicker detect changes and put the versions in manually.

Thanks for the update!

**Comment by jlesage** [comment]
I use an RSS feed to be aware of new versions as they are available.  Usually it doesn't take too long to update and provide a new Docker image, but that depends how much I'm busy on other things :)
