### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by ionush** [jlesage/docker-filezilla#41]
I can only write to folders that have my unix user permission (i.e. /home/myUserName). Writing to folders with root ownership doesn't work even though I run docker with ```sudo docker run...```

**Comment by jlesage** [comment]
The container itself doesn't as root.  Processes inside the container run as the user configured by `USER_ID`/`GROUP_ID` environment variables.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
