### ISSUE TITLE
Volume set to Nas Storage Public folder

### ISSUE THREAD

**Issue by CrownParkComputing** [jlesage/docker-filezilla#42]
I am trying to mount my NAS public folder to the storage location. The path is in the attached. please help, been trying to figure this out from many tutorials !

![Screenshot 2022-09-10 204513](https://user-images.githubusercontent.com/35380922/189499465-e54f7584-a429-4e8d-96f9-c23e1dedbced.png)

**Comment by jlesage** [comment]
If you use the container station, there is a tab in container settings called "Shared Folder" where you can map folders on the NAS to the container.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
