### ISSUE TITLE
question on the gui 

### ISSUE THREAD

**Issue by cosmic-tiger** [jlesage/docker-filezilla#44]
Hi,
Can I ask if this is a bootstrap gui / Is it an expressjs application?

I couldn't find the code in this github site. Can I see it or is it not available (sorry, maybe i was looking in the wrong place)

Thanks

**Comment by jlesage** [comment]
The web UI is an implementation of noVNC (https://github.com/novnc/noVNC), an HTML VNC client.

This container is using the following baseimage, where most of core functionality is implemented: https://github.com/jlesage/docker-baseimage-gui

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
