### ISSUE TITLE
v1.36.0 = fzsftp could not be started

### ISSUE THREAD

**Issue by MartinHotmann** [jlesage/docker-filezilla#45]
Same old issue: https://github.com/jlesage/docker-filezilla/issues/27
since v1.36.0 (3.61.0) again. Is it again fixable, or do I need to stay at v1.35.4 (3.60.2)?

Thanks in advance!

**Comment by jlesage** [comment]
With the latest FileZilla version, I saw that the code causing the issue was not there anymore.  But I think it may have been moved to the libfilezilla library.  Let me check that...

**Comment by MartinHotmann** [comment]
Yeaaaaah ❤️
You are a f*cking legend! v1.36.1 works again.

Thanks!
