### ISSUE TITLE
Container cannot run anymore

### ISSUE THREAD

**Issue by PatrickHsu36** [jlesage/docker-filezilla#47]
Hello,
I deploy FileZilla and JDownloader-2 containers and works well for a long time on Linux amd64 platform.
After I pull the latest image and deploy the container, it failed to start after the version 1.7.2.
The issue may be there already after the versioning is changed to align the date and support more platforms.
I can only see the error as the followings:

[cont-init   ] 89-info.sh: executing...
    ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮

    │                                                                      │

    │ Application:           FileZilla                                     │

    │ Application Version:   3.62.2                                        │

    │ Docker Image Version:  23.01.1                                       │

    │ Docker Image Platform: linux/amd64                                   │

    │                                                                      │

    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯

[cont-init   ] 89-info.sh: terminated successfully.

[cont-init   ] all container initialization scripts executed.

[init        ] giving control to process supervisor.

[supervisor  ] loading services...

[supervisor  ] loading service 'default'...

[supervisor  ] could not load 'app.dep': command failed (126)

[finish      ] executing container finish scripts...

[finish      ] all container finish scripts executed.

BTW, same error is found on JDownloader2 container.
Any possible root cause and solutions?
Thanks a lot.

**Comment by jlesage** [comment]
On what device are your running the container ?

**Comment by PatrickHsu36** [comment]
Hello,

I use the container in ASUSTOR NAS with Intel CPU and Linux kernel.

Thanks a lot.
Best regards,


Jocelyn Le Sage ***@***.***> 於 2023年1月12日 週四 下午9:29寫道：

**Comment by jlesage** [comment]
Forgot to update this issue, but the I think the latest image should work now ?

**Comment by PatrickHsu36** [comment]
Sorry for late reply.
Yes, I just try the latest version (23.03.1), the container works now.
Thanks a lot.
