### ISSUE TITLE
Error: Critical File transfer error 

### ISSUE THREAD

**Issue by VinneyUK** [jlesage/docker-filezilla#48]
Hi,
I've deployed the container fine and logged into a FTP server using the web GUI however when I try and transfer any files I get the following error in the log window:

**Error: Critical file transfer error**

Any ideas?, please 🙏

**Comment by jlesage** [comment]
Can you share a screenshot of the the error ?
Do you have the same issue with any FTP server ?
Does the location where you save the file makes a difference (e.g. do you have the same problem if you download to `/tmp`)?

**Comment by VinneyUK** [comment]
Hey I don't get the error when downloading to the /tmp dir? How do I use dir my choice?

**Comment by jlesage** [comment]
Normally when you create the container you configure a volume to map the `/storage` inside the container to a folder of your choice on the host.
How did you create the container ?

**Comment by VinneyUK** [comment]
Hey thanks for replying. See attached 
`filezilla:
    image: jlesage/filezilla
    container_name: filezilla
    # ports:
    # - "5800:5800"
    volumes:
      - /home/dietpi/filezilla:/config:rw
      - /mnt/shared:/storage:rw
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn `

**Comment by jlesage** [comment]
So you need to make sure that `/mnt/shared` has proper permissions/ownership to allow writes from the container's user, which is controlled by `USER_ID` and `GROUP_ID` environment variables.
See https://github.com/jlesage/docker-filezilla#usergroup-ids

**Comment by jyubonk** [comment]
Hi,

I have the same issue.

I have make sure that my storage has proper permissions/ownership - also edited environement variables with proper user id and group id but still cannot download files into my storage - show critical file transfer error

**Comment by jlesage** [comment]
Do you have the same issue if you download to `/tmp`?  If no, then the problem points to a permission issue.

**Comment by jyubonk** [comment]
> Do you have the same issue if you download to `/tmp`? If no, then the problem points to a permission issue.

Yes, I able to download to tmp folder - how to fix the permissions issue? On my NAS, the path involved already have permissions for read and write

**Comment by jyubonk** [comment]
Nevermind - i figure it out. Thanks! Works like a charm now.

**Comment by jlesage** [comment]
Great ! Closing this issue.
