### ISSUE TITLE
Download speed seems to be capped at 2.0 mbps per file

### ISSUE THREAD

**Issue by whoindahouse** [jlesage/docker-filezilla#49]
Connecting to an external FTP from my Synology DS918+ NAS running Docker and this Filezilla container. Everything transfers correctly but seems to be capped at ~2.0 mb/s. I connected to the same external FTP from my MacBook Air using Filezilla with same server settings and achieved 20+ mb/s from transfers on individual files. Any advice is welcome. Thanks

**Comment by jlesage** [comment]
I did a quick test on my side and I was able to reach +12mbps without issue.
Maybe some restrictions in place on your Synology ?

**Comment by whoindahouse** [comment]
Is the container on bridge or host network?

**Comment by jlesage** [comment]
I use the default bridge network.

**Comment by jlesage** [comment]
Do you have any update on this ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
