### ISSUE TITLE
Error on exit

### ISSUE THREAD

**Issue by C4Wiz** [jlesage/docker-filezilla#5]
when exiting the docker from the WebUI i get the following error:

file menu --> exit

<img width="666" alt="screen shot 2018-01-24 at 8 58 24 am" src="https://user-images.githubusercontent.com/3883521/35342330-073b3e96-00e5-11e8-9006-1b00238e8541.png">

**Comment by jlesage** [comment]
I'm not able to reproduce.  Do you have to do anything special? Did you pulled the latest image?  Also, can you provide the docker command you use to run the container?

**Comment by C4Wiz** [comment]
in the Filezilla WebUI goto file, then exit. it happens everytime

to start the docker i goto dockers tab in unRAID webui, click on the filezilla icon and hit start

i am using the latest image yes

here is the log`[logmonitor] no file to monitor: disabling service...
[services.d] starting xvfb...
[certsmonitor] disabling service: secure connection not enabled.
[nginx] starting...
[xvfb] starting...
[services.d] starting openbox...
[openbox] starting...
Openbox-Message: Openbox was compiled without image loading support. Icons in menus will not be loaded.
[services.d] starting x11vnc...
[services.d] starting app...
[x11vnc] starting...
[app] starting FileZilla...
[services.d] done.
23/01/2018 15:22:02 passing arg to libvncserver: -rfbport
23/01/2018 15:22:02 passing arg to libvncserver: 5900
23/01/2018 15:22:02 passing arg to libvncserver: -rfbportv6
23/01/2018 15:22:02 passing arg to libvncserver: -1
23/01/2018 15:22:02 passing arg to libvncserver: -httpportv6
23/01/2018 15:22:02 passing arg to libvncserver: -1
23/01/2018 15:22:02 passing arg to libvncserver: -desktop
23/01/2018 15:22:02 passing arg to libvncserver: FileZilla
23/01/2018 15:22:02 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 741

23/01/2018 15:22:02 Using X display :0
23/01/2018 15:22:02 rootwin: 0x43 reswin: 0x400001 dpy: 0x6ecd8a00
23/01/2018 15:22:02
23/01/2018 15:22:02 ------------------ USEFUL INFORMATION ------------------
23/01/2018 15:22:02 X DAMAGE available on display, using it for polling hints.
23/01/2018 15:22:02 To disable this behavior use: '-noxdamage'
23/01/2018 15:22:02
23/01/2018 15:22:02 Most compositing window managers like 'compiz' or 'beryl'
23/01/2018 15:22:02 cause X DAMAGE to fail, and so you may not see any screen
23/01/2018 15:22:02 updates via VNC. Either disable 'compiz' (recommended) or
23/01/2018 15:22:02 supply the x11vnc '-noxdamage' command line option.
23/01/2018 15:22:02 X COMPOSITE available on display, using it for window polling.
23/01/2018 15:22:02 To disable this behavior use: '-noxcomposite'
23/01/2018 15:22:02
23/01/2018 15:22:02 Wireframing: -wireframe mode is in effect for window moves.
23/01/2018 15:22:02 If this yields undesired behavior (poor response, painting
23/01/2018 15:22:02 errors, etc) it may be disabled:
23/01/2018 15:22:02 - use '-nowf' to disable wireframing completely.
23/01/2018 15:22:02 - use '-nowcr' to disable the Copy Rectangle after the
23/01/2018 15:22:02 moved window is released in the new position.
23/01/2018 15:22:02 Also see the -help entry for tuning parameters.
23/01/2018 15:22:02 You can press 3 Alt_L's (Left "Alt" key) in a row to
23/01/2018 15:22:02 repaint the screen, also see the -fixscreen option for
23/01/2018 15:22:02 periodic repaints.
23/01/2018 15:22:02 GrabServer control via XTEST.
23/01/2018 15:22:02
23/01/2018 15:22:02 Scroll Detection: -scrollcopyrect mode is in effect to
23/01/2018 15:22:02 use RECORD extension to try to detect scrolling windows
23/01/2018 15:22:02 (induced by either user keystroke or mouse input).

23/01/2018 15:22:02 If this yields undesired behavior (poor response, painting
23/01/2018 15:22:02 errors, etc) it may be disabled via: '-noscr'
23/01/2018 15:22:02 Also see the -help entry for tuning parameters.
23/01/2018 15:22:02 You can press 3 Alt_L's (Left "Alt" key) in a row to
23/01/2018 15:22:02 repaint the screen, also see the -fixscreen option for
23/01/2018 15:22:02 periodic repaints.
23/01/2018 15:22:02
23/01/2018 15:22:02 XKEYBOARD: number of keysyms per keycode 7 is greater
23/01/2018 15:22:02 than 4 and 51 keysyms are mapped above 4.
23/01/2018 15:22:02 Automatically switching to -xkb mode.
23/01/2018 15:22:02 If this makes the key mapping worse you can
23/01/2018 15:22:02 disable it with the "-noxkb" option.
23/01/2018 15:22:02 Also, remember "-remap DEAD" for accenting characters.
23/01/2018 15:22:02
23/01/2018 15:22:02 X FBPM extension not supported.
23/01/2018 15:22:02 X display is not capable of DPMS.
23/01/2018 15:22:02 --------------------------------------------------------
23/01/2018 15:22:02
23/01/2018 15:22:02 Default visual ID: 0x21
23/01/2018 15:22:02 Read initial data from X display into framebuffer.
23/01/2018 15:22:02 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/7680
23/01/2018 15:22:02
23/01/2018 15:22:02 X display :0 is 32bpp depth=24 true color
23/01/2018 15:22:02
23/01/2018 15:22:02 Listening for VNC connections on TCP port 5900
23/01/2018 15:22:02
23/01/2018 15:22:02 Xinerama is present and active (e.g. multi-head).
23/01/2018 15:22:02 Xinerama: number of sub-screens: 1
23/01/2018 15:22:02 Xinerama: no blackouts needed (only one sub-screen)
23/01/2018 15:22:02
23/01/2018 15:22:02 fb read rate: 1678 MB/sec
23/01/2018 15:22:02 fast read: reset -wait ms to: 10
23/01/2018 15:22:02 fast read: reset -defer ms to: 10
23/01/2018 15:22:02 The X server says there are 10 mouse buttons.

23/01/2018 15:22:02 screen setup finished.
23/01/2018 15:22:02

The VNC desktop is: caad9732f60d:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

Reading locale option from /config/xdg/config/filezilla/filezilla.xml
23/01/2018 15:26:05 Got connection from client 127.0.0.1
23/01/2018 15:26:05 other clients:
23/01/2018 15:26:05 Got 'ws' WebSockets handshake
23/01/2018 15:26:05 Got protocol: binary
23/01/2018 15:26:05 - webSocketsHandshake: using binary/raw encoding
23/01/2018 15:26:05 - WebSockets client version hybi-13

23/01/2018 15:26:05 Disabled X server key autorepeat.
23/01/2018 15:26:05 to force back on run: 'xset r on' (3 times)
23/01/2018 15:26:05 incr accepted_client=1 for 127.0.0.1:44004 sock=10
23/01/2018 15:26:05 Client Protocol Version 3.8

23/01/2018 15:26:05 Protocol version sent 3.8, using 3.8

23/01/2018 15:26:05 rfbProcessClientSecurityType: executing handler for type 1
23/01/2018 15:26:05 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8

23/01/2018 15:26:05 Pixel format for client 127.0.0.1:
23/01/2018 15:26:05 32 bpp, depth 24, little endian
23/01/2018 15:26:05 true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
23/01/2018 15:26:05 no translation needed
23/01/2018 15:26:05 Enabling NewFBSize protocol extension for client 127.0.0.1
23/01/2018 15:26:05 Enabling full-color cursor updates for client 127.0.0.1
23/01/2018 15:26:05 Using image quality level 6 for client 127.0.0.1
23/01/2018 15:26:05 Using JPEG subsampling 0, Q79 for client 127.0.0.1
23/01/2018 15:26:05 Using compression level 9 for client 127.0.0.1
23/01/2018 15:26:05 Enabling LastRect protocol extension for client 127.0.0.1
23/01/2018 15:26:05 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)
23/01/2018 15:26:05 Using tight encoding for client 127.0.0.1
23/01/2018 15:26:06 client_set_net: 127.0.0.1 0.0001
23/01/2018 15:26:06 created xdamage object: 0x400040
23/01/2018 15:26:06 copy_tiles: allocating first_line at size 61
23/01/2018 15:26:09 client 1 network rate 1256.5 KB/sec (29966.6 eff KB/sec)
23/01/2018 15:26:09 client 1 latency: 1.6 ms
23/01/2018 15:26:09 dt1: 0.0127, dt2: 0.0017 dt3: 0.0016 bytes: 18074
23/01/2018 15:26:09 link_rate: LR_LAN - 1 ms, 1256 KB/s
23/01/2018 15:26:14 created selwin: 0x400041
23/01/2018 15:26:14 called initialize_xfixes()
23/01/2018 15:31:06 idle keyboard: turning X autorepeat back on.

./src/gtk/dialog.cpp(199): assert "Assert failure" failed in EndModal(): either wxDialog:EndModal called twice or ShowModal wasn't called

24/01/2018 15:58:24 active keyboard: waiting until all keys are up. key_down=50 Shift_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:24 active keyboard: waiting until all keys are up. key_down=64 Alt_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:24 active keyboard: waiting until all keys are up. key_down=133 Super_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:26 active keyboard: waiting until all keys are up. key_down=50 Shift_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:26 active keyboard: waiting until all keys are up. key_down=64 Alt_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:26 active keyboard: waiting until all keys are up. key_down=133 Super_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:28 active keyboard: waiting until all keys are up. key_down=50 Shift_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:28 active keyboard: waiting until all keys are up. key_down=64 Alt_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:28 active keyboard: waiting until all keys are up. key_down=133 Super_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:30 active keyboard: waiting until all keys are up. key_down=50 Shift_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:30 active keyboard: waiting until all keys are up. key_down=64 Alt_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:30 active keyboard: waiting until all keys are up. key_down=133 Super_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:32 active keyboard: waiting until all keys are up. key_down=50 Shift_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:32 active keyboard: waiting until all keys are up. key_down=64 Alt_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:32 active keyboard: waiting until all keys are up. key_down=133 Super_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

24/01/2018 15:58:34 active keyboard: waiting until all keys are up. key_down=133 Super_L. If the key is inaccessible via keyboard, consider 'x11vnc -R clear_all'

[services.d] stopping services
[services.d] stopping app...
[services.d] stopping x11vnc...
caught signal: 15
24/01/2018 15:58:35 deleted 60 tile_row polling images.
[services.d] stopping openbox...
[services.d] stopping xvfb...
[services.d] stopping nginx...
[services.d] stopping logmonitor...
[services.d] stopping certsmonitor...
[services.d] stopping statusmonitor...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] filezilla.sh: executing...
Generating machine-id...
[cont-init.d] filezilla.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting logmonitor...
[services.d] starting statusmonitor...
[logmonitor] no file to monitor: disabling service...
[services.d] starting certsmonitor...
[statusmonitor] no file to monitor: disabling service...
[services.d] starting nginx...
[services.d] starting xvfb...
[certsmonitor] disabling service: secure connection not enabled.
[nginx] starting...
[xvfb] starting...
[services.d] starting openbox...
[openbox] starting...
Openbox-Message: Openbox was compiled without image loading support. Icons in menus will not be loaded.
[services.d] starting x11vnc...
[x11vnc] starting...
[services.d] starting app...
24/01/2018 17:58:19 passing arg to libvncserver: -rfbport
24/01/2018 17:58:19 passing arg to libvncserver: 5900
24/01/2018 17:58:19 passing arg to libvncserver: -rfbportv6
24/01/2018 17:58:19 passing arg to libvncserver: -1
24/01/2018 17:58:19 passing arg to libvncserver: -httpportv6
24/01/2018 17:58:19 passing arg to libvncserver: -1
24/01/2018 17:58:19 passing arg to libvncserver: -desktop
24/01/2018 17:58:19 passing arg to libvncserver: FileZilla
24/01/2018 17:58:19 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 774

24/01/2018 17:58:19 Using X display :0
24/01/2018 17:58:19 rootwin: 0x43 reswin: 0x400001 dpy: 0xbb0cda00
24/01/2018 17:58:19
24/01/2018 17:58:19 ------------------ USEFUL INFORMATION ------------------
[app] starting FileZilla...
[services.d] done.
24/01/2018 17:58:19 X DAMAGE available on display, using it for polling hints.
24/01/2018 17:58:19 To disable this behavior use: '-noxdamage'
24/01/2018 17:58:19
24/01/2018 17:58:19 Most compositing window managers like 'compiz' or 'beryl'
24/01/2018 17:58:19 cause X DAMAGE to fail, and so you may not see any screen
24/01/2018 17:58:19 updates via VNC. Either disable 'compiz' (recommended) or
24/01/2018 17:58:19 supply the x11vnc '-noxdamage' command line option.
24/01/2018 17:58:19 X COMPOSITE available on display, using it for window polling.
24/01/2018 17:58:19 To disable this behavior use: '-noxcomposite'
24/01/2018 17:58:19
24/01/2018 17:58:19 Wireframing: -wireframe mode is in effect for window moves.
24/01/2018 17:58:19 If this yields undesired behavior (poor response, painting
24/01/2018 17:58:19 errors, etc) it may be disabled:
24/01/2018 17:58:19 - use '-nowf' to disable wireframing completely.
24/01/2018 17:58:19 - use '-nowcr' to disable the Copy Rectangle after the
24/01/2018 17:58:19 moved window is released in the new position.
24/01/2018 17:58:19 Also see the -help entry for tuning parameters.
24/01/2018 17:58:19 You can press 3 Alt_L's (Left "Alt" key) in a row to
24/01/2018 17:58:19 repaint the screen, also see the -fixscreen option for
24/01/2018 17:58:19 periodic repaints.
24/01/2018 17:58:19 GrabServer control via XTEST.
24/01/2018 17:58:19
24/01/2018 17:58:19 Scroll Detection: -scrollcopyrect mode is in effect to
24/01/2018 17:58:19 use RECORD extension to try to detect scrolling windows
24/01/2018 17:58:19 (induced by either user keystroke or mouse input).

24/01/2018 17:58:19 If this yields undesired behavior (poor response, painting
24/01/2018 17:58:19 errors, etc) it may be disabled via: '-noscr'
24/01/2018 17:58:19 Also see the -help entry for tuning parameters.
24/01/2018 17:58:19 You can press 3 Alt_L's (Left "Alt" key) in a row to
24/01/2018 17:58:19 repaint the screen, also see the -fixscreen option for
24/01/2018 17:58:19 periodic repaints.
24/01/2018 17:58:19
24/01/2018 17:58:19 XKEYBOARD: number of keysyms per keycode 7 is greater
24/01/2018 17:58:19 than 4 and 51 keysyms are mapped above 4.
24/01/2018 17:58:19 Automatically switching to -xkb mode.
24/01/2018 17:58:19 If this makes the key mapping worse you can
24/01/2018 17:58:19 disable it with the "-noxkb" option.
24/01/2018 17:58:19 Also, remember "-remap DEAD" for accenting characters.
24/01/2018 17:58:19
24/01/2018 17:58:19 X FBPM extension not supported.
24/01/2018 17:58:19 X display is not capable of DPMS.
24/01/2018 17:58:19 --------------------------------------------------------
24/01/2018 17:58:19
24/01/2018 17:58:19 Default visual ID: 0x21
24/01/2018 17:58:19 Read initial data from X display into framebuffer.
24/01/2018 17:58:19 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/7680
24/01/2018 17:58:19
24/01/2018 17:58:19 X display :0 is 32bpp depth=24 true color
24/01/2018 17:58:19
24/01/2018 17:58:19 Listening for VNC connections on TCP port 5900
24/01/2018 17:58:19
24/01/2018 17:58:19 Xinerama is present and active (e.g. multi-head).
24/01/2018 17:58:19 Xinerama: number of sub-screens: 1
24/01/2018 17:58:19 Xinerama: no blackouts needed (only one sub-screen)
24/01/2018 17:58:19
24/01/2018 17:58:19 fb read rate: 1387 MB/sec
24/01/2018 17:58:19 fast read: reset -wait ms to: 10
24/01/2018 17:58:19 fast read: reset -defer ms to: 10
24/01/2018 17:58:19 The X server says there are 10 mouse buttons.

24/01/2018 17:58:19 screen setup finished.
24/01/2018 17:58:19

The VNC desktop is: caad9732f60d:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

Reading locale option from /config/xdg/config/filezilla/filezilla.xml
24/01/2018 17:58:55 Got connection from client 127.0.0.1
24/01/2018 17:58:55 other clients:
24/01/2018 17:58:55 Got 'ws' WebSockets handshake
24/01/2018 17:58:55 Got protocol: binary
24/01/2018 17:58:55 - webSocketsHandshake: using binary/raw encoding
24/01/2018 17:58:55 - WebSockets client version hybi-13

24/01/2018 17:58:55 Disabled X server key autorepeat.
24/01/2018 17:58:55 to force back on run: 'xset r on' (3 times)
24/01/2018 17:58:55 incr accepted_client=1 for 127.0.0.1:44646 sock=10
24/01/2018 17:58:55 Client Protocol Version 3.8

24/01/2018 17:58:55 Protocol version sent 3.8, using 3.8

24/01/2018 17:58:55 rfbProcessClientSecurityType: executing handler for type 1
24/01/2018 17:58:55 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8

24/01/2018 17:58:55 Pixel format for client 127.0.0.1:
24/01/2018 17:58:55 32 bpp, depth 24, little endian
24/01/2018 17:58:55 true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
24/01/2018 17:58:55 no translation needed
24/01/2018 17:58:55 Enabling NewFBSize protocol extension for client 127.0.0.1
24/01/2018 17:58:55 Enabling full-color cursor updates for client 127.0.0.1
24/01/2018 17:58:55 Using image quality level 6 for client 127.0.0.1
24/01/2018 17:58:55 Using JPEG subsampling 0, Q79 for client 127.0.0.1
24/01/2018 17:58:55 Using compression level 9 for client 127.0.0.1
24/01/2018 17:58:55 Enabling LastRect protocol extension for client 127.0.0.1
24/01/2018 17:58:55 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)
24/01/2018 17:58:55 Using tight encoding for client 127.0.0.1
24/01/2018 17:58:56 client_set_net: 127.0.0.1 0.0001
24/01/2018 17:58:56 created xdamage object: 0x400040
24/01/2018 17:58:56 copy_tiles: allocating first_line at size 61
24/01/2018 17:58:58 client 1 network rate 333.4 KB/sec (9540.8 eff KB/sec)
24/01/2018 17:58:58 client 1 latency: 1.7 ms
24/01/2018 17:58:58 dt1: 0.0063, dt2: 0.1419 dt3: 0.0017 bytes: 49138
24/01/2018 17:58:58 link_rate: LR_LAN - 1 ms, 333 KB/s
24/01/2018 17:59:05 created selwin: 0x400041
24/01/2018 17:59:05 called initialize_xfixes()
24/01/2018 18:04:22 idle keyboard: turning X autorepeat back on.`

**Comment by jlesage** [comment]
Did you change any setting?
Also, can you try to run the container with a different/empty appdata?

**Comment by C4Wiz** [comment]
i cleared the appdata folder for filezilla, started the container, then exited like above, no error.

i then copied my setting back in, started the container, setting were correct. exited container like above, no error!

looks like the settings location has changed from /appdata/filezilla/ to /appdata/filezilla/xdg/config/filezilla

i had settings in both locations

**Comment by jlesage** [comment]
So if you restore the same content of appdata, are you able to reproduce again?

**Comment by C4Wiz** [comment]
didnt try, already deleted the old folder. it works now, i don't want to rock the boat

**Comment by jlesage** [comment]
Ok no problem, just wanted to see if it's something that could be fixed automatically.
Thanks!
