### ISSUE TITLE
[Feature request] Dark Mode

### ISSUE THREAD

**Issue by C4Wiz** [jlesage/docker-filezilla#52]
### Idea

Can we get dark mode like in the MakeMKV container please?

**Comment by jlesage** [comment]
Yes it's already supported.

For example, you have have a dark interface when running:
```
docker run --rm -ti -p 5800:5800 -e DARK_MODE=1 jlesage/filezilla
```

**Comment by C4Wiz** [comment]
Sorry, i am using a old unRAID template from before Dark Mode was Added, i just added the Variable to my template and it works perfectly. thanks

**Comment by jlesage** [comment]
No problem.  It's too bad that unRAID is no longer updating template of installed containers... :(
