### ISSUE TITLE
File Synchronization

### ISSUE THREAD

**Issue by TerrorSource** [jlesage/docker-filezilla#54]
### Idea

Hi,

Docker works fine with connecting to different servers. 
I saw that the normal Filezilla has "File Synchronization" build-in but it is missing in the Docker.

Are you able to add it?
https://filezillapro.com/docs/v3/advanced/file-synchronization/

**Comment by jlesage** [comment]
Is this feature apply only to the pro version ?

**Comment by jlesage** [comment]
It seems that it's the case: https://filezillapro.com/docs/v3/basic-usage-instructions/difference-between-filezilla-and-filezilla-pro/

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
