### ISSUE TITLE
Connecting my web container to the filezilla container.

### ISSUE THREAD

**Issue by aneshranjit** [jlesage/docker-filezilla#6]
Hi @jlesage ,
This is not really an issue, just me asking your help.
I've been trying to use your image in my docker-compose file and I can't seem to do it right.
All container runs successfully but I can't access my files in my filezilla application.
Here's the content on my docker-compose.yaml:

> version: '3.2' 
services:
  database:
	image: percona
	container_name: try_db
	environment:
	  - MYSQL_ROOT_PASSWORD=root
	  - MYSQL_DATABASE=db_try
	ports:
	  - "3306:3306"  
	networks:
	  - try-net
  web:
	image: webdevops/php-nginx
	container_name: try_web
	ports:
	  - "80:80"
	  - "443:443"
	volumes:
	  - ./files/sync:/var/www/sync
	environment:
	  WEB_DOCUMENT_ROOT: /var/www
	  DB_HOST: database:3306
	networks:
	  - try-net
  filezilla:
	image: jlesage/filezilla
	container_name: try_filezilla
	ports:
	  - "5800:5800"
	  - "5900:5900"
	volumes:
	  - "/docker/appdata/filezilla:/config:rw"
	  - "/files:/storage:rw"
	environment:
	  - VNC_PASSWORD=admin123
	networks:
	  - try-net
networks:
  try-net:

[docker-compose.yaml.txt](https://github.com/jlesage/docker-filezilla/files/2418148/docker-compose.yaml.txt)

What I'm basically trying to do is access the files in my web container via filezilla application.
Could you please tell me what I'm doing wrong and what I should be doing?

Regards.

**Comment by jlesage** [comment]
For your web container, you have set the volume to `./files/sync:/var/www/sync:/var/www/sync`.  Are you sure you need the initial dot?  I would try `/files/sync:/var/www/sync:/var/www/sync` to match what you have for the filezilla container.

**Comment by jlesage** [comment]
Closing the issue.  Please re-open if needed.
