### ISSUE TITLE
cannot connect to running filezilla server

### ISSUE THREAD

**Issue by baumar** [jlesage/docker-filezilla#7]
Hi, 

I ran the filezilla docker container like this:

docker run --name=filezilla --user 501 -p5800:5800 -v /Users/.../data/filezilla/filezilla_extstore:/store jlesage/filezilla 

Seems as it is running:

7752bcbeb90a        jlesage/filezilla   "/init"             22 seconds ago      Up 20 seconds       0.0.0.0:5800->5800/tcp, 5900/tcp   filezilla

but I cannot connect to it. 

Maybe this is because of the uid and gid you mention. I tried to add it with
docker run --name=filezilla --user 501 -p5800:5800 -v /Users/.../data/filezilla/filezilla_extstore:/storeonhost jlesage/filezilla 
but it didn't run. 

Could you pls give me a hint or even better write in the documentation or in a tutorial how to set up the server correctly (maybe with a docker file ?) and then connect to it? 

thanks for help
PS I'm relatively new to docker filezilla, sorry if I fight with basics...

**Comment by jlesage** [comment]
Note that this docker container is the FileZilla FTP client.  It's not an FTP server.   Is it what you are looking for?

**Comment by jlesage** [comment]
Closing the issue.  Please re-open if needed.
